### ISSUE TITLE
Something wrong with the image

### ISSUE THREAD

**Issue by rchamseddine** [NebraLtd/helium-rak#1]
Hi,

I just added my rak v2 to for the test. But apparently two issues:
1) Major: The hotspot became un-usable. First I could not pair bt to it. When I click the button on the hs, I could not find the device after scanning. I did that in 10min apart and did a couple of restarts of the device nothing help. 
2) Even after 30 min I could not ping the hs at all.

**Comment by VanThongTomTo** [comment]
+1 Also can't connect via bluetooth

**Comment by arduino43** [comment]
Try adding the VARIANT variable in Balena.io and set value to "COMP-RAKHM"

**Comment by shawaj** [comment]
The Bluetooth issue is fixed now 👍
