### ISSUE TITLE
Failed to download image error with newest release

### ISSUE THREAD

**Issue by Turb0n00by** [NebraLtd/helium-rak#11]
Hi,

After pulling down and pushing the newest image as of a couple hours ago. I am not seeing the repeated message. Is this a cause for concern?

Failed to download image 'registry2.balena-cloud.com/v2/3a33a7e2c9fa20026037df5ec9e2c000@sha256:29c1c05c9aa2b623e4bdf2e2497a00338322d6c6e952317dd42d0898573f42b4' due to 'layers from manifest don't match image configuration"

Im noticing within the console the components "helium-Miner", "gateway"... The helium miner attempts to download before getting the error message above. The other components look to be sitting in queue. Firmware under the diagnostic service is still showing the device running fw from 6/02/2022.  I have attempted to restart the miner but it reverts back to this state. Should I rollback if possible?
<img width="405" alt="Screen Shot 2022-06-13 at 4 24 44 PM" src="https://user-images.githubusercontent.com/51140610/173448063-16321e3b-17d6-4dc3-90ef-33984580fb0d.png">
<img width="429" alt="Screen Shot 2022-06-13 at 4 50 54 PM" src="https://user-images.githubusercontent.com/51140610/173451306-8ed98480-cf08-474f-bb2e-ff12aaf8c4e7.png">

**Comment by shawaj** [comment]
The idea behind this is you are supposed to run it using balenaHub rather than directly on balenaCloud.

https://nebra.io/rak

But having said that, looks like you should try purging the device from the actions menu and see if it will redownload the containers.

**Comment by Turb0n00by** [comment]
Hey Shaw thanks for the response,

I do run this from the provided URL, when it comes to updates I manually DL the source code from here and using Balena CLI I upload the image/release to my workspace in Balena hub. 

I will give that a shot, though it seems like its the miner service itself that attempts to download, then fails with the error above. I'll give what you said a try and let you know.

**Comment by Turb0n00by** [comment]
Ok So I purged everything and started fresh and can confirm what trying to use the latest release the helium-miner service crashes when trying to either download or verify its download via the error above. If I revert to 6/10 we seem to be back to normal.

**Comment by ifeign** [comment]
> Hey Shaw thanks for the response,
> 
> I do run this from the provided URL, when it comes to updates I manually DL the source code from here and using Balena CLI I upload the image/release to my workspace in Balena hub.
> 
> I will give that a shot, though it seems like its the miner service itself that attempts to download, then fails with the error above. I'll give what you said a try and let you know.

You don't need to do all of that, you can just hit the fork fleet button again and it will give you the option to apply the latest image to your existing fleet

**Comment by Turb0n00by** [comment]
> You don't need to do all of that, you can just hit the fork fleet button again and it will give you the option to apply the latest image to your existing fleet

Ill try that again and let you know.

I’m assuming these won’t need port forwarding enabled and I can close the port again? (Though I have had conflicting experiences when doing this)..

I went back tried the "get started" setup as asked but I found I did not have access to the dashboard of the device like I do when I forked it. I am OK with having to manually update it, I really dont want to lose my dashboard and other controls if possible. If that means loosing BT functionality I am fine with it too.

**Comment by shawaj** [comment]
You can also just set up automations using GitHub to automatically push new updates when we release them. 

But that's a bit more involved to do yourself.

However, it is on our list to create a guide for this and perhaps a one click way to do this if we can

**Comment by ifeign** [comment]
> You can also just set up automations using GitHub to automatically push new updates when we release them. 
> 
> 
> 
> But that's a bit more involved to do yourself.
> 
> 
> 
> However, it is on our list to create a guide for this and perhaps a one click way to do this if we can

I've been meaning to get something set up using actions to fork and sync this repo, then push it to balena via their api.. just haven't had time to dedicate to it. If you guys offer a tutorial, you'll have a very grateful DIY community!

**Comment by Turb0n00by** [comment]
If I can help you guys out please let me know!

**Comment by shawaj** [comment]
Most of the tooling is already, in a roundabout way, in our main helium-miner-software repo. Just needs to be made pretty and a little tutorial set up.

We are actually working with Balena to add support for more hardware variants and better guides and info for this and hoping to get a Helium Foundation grant to support this as well

**Comment by ifeign** [comment]
That’s wonderful. If funding is something that’s needed, I’m sure some of
us would donate if you put a link up, I personally have been very grateful
for this firmware. Actually makes my RAK enjoyable to use.

**Comment by shawaj** [comment]
We are actually also in the process of setting up GitHub Sponsors for this very reason :-)

Dedicating engineering hours to this is something we love doing but we have a quite large backlog internally so the amount of time we can actually dedicate to the open source side is dwindling which is frustrating. So yeah any donations and grants will make a massive difference. Our hope is to be able to dedicate some people to do this full time. 

IMO, it's key to the decentralisation of the network as well.

**Comment by Turb0n00by** [comment]
I second that. Thank you so much for putting in the time and efforts here.

**Comment by shawaj** [comment]
@Turb0n00by @ifeign just set up GitHub Sponsors - it is still very much a work in progress but you can chuck us some sponsorship there https://github.com/sponsors/NebraLtd

**Comment by shawaj** [comment]
Thanks @ifeign - that was super quick. Your support is much appreciated!

**Comment by ifeign** [comment]
> 

Of course! Gotta put my money where my mouth is

**Comment by Turb0n00by** [comment]
Done n Done

**Comment by shawaj** [comment]
You guys are awesome, thanks.

Also I'm halfway through writing a guide for how to deploy using balenaHub and how to deploy by forking 👍

**Comment by Turb0n00by** [comment]
Thanks again Shaw!

If I could ask (Maybe it exists somewhere already), do you guys posts a change log here when you update your docker.yml files? I'm attempting to learn this stuff more in depth.

**Comment by shawaj** [comment]
We don't currently have a detailed changelog I'm afraid. I think we are planning to buy it has not yet been implemented.
