### ISSUE TITLE
Provide some instructions please

### ISSUE THREAD

**Issue by lt-columbo** [NebraLtd/helium-rak#12]
This page says there are detailed instructions: https://www.nebra.com/blogs/news/production-update-firmware-support-for-third-party-miners-spring-sale-existing-customer-discount-and-more --> here: https://github.com/NebraLtd/helium-rak Yet there is nothing there. I'd give this a try if there was at least a hint of how to install it, what to do after booting, how I might know it's actually working, does it really have a dashboard? I already have a miner without a dashboard, and going through this without any gain isn't a good use of my time.

**Comment by ronmis** [comment]
Follow these instructions - https://www.reddit.com/r/HeliumNetwork/comments/ut9jlk/nebra_dashboard_for_rak_miners/

**Comment by shawaj** [comment]
Have a look at the instructions here https://support.nebra.com/support/solutions/articles/24000078640-getting-started-with-rak-mntd

Or in the readme for this repo: https://github.com/NebraLtd/helium-rak/blob/master/README.md
