### ISSUE TITLE
Question about public IP address changing

### ISSUE THREAD

**Issue by Turb0n00by** [NebraLtd/helium-rak#13]
Hello,

Just a quick question. I noticed that my miner has not really done much of anything for the past 3-4 days now and was starting to scratch my head as to why. I noticed my ISP has issued a new public IP to me and within the balena dashboard it is still reporting my previous public IP. 

Will this have a negative impact, should I see what I can do to get my new IP to match up from the balena console?

Thank you in advanced

**Comment by Crash0v3r1de** [comment]
sounds like you're referring to your local IP address and not public IP address. Balena dashboard shows both of those IP's.

**Comment by pritamghanghas** [comment]
In either case, these days your public IP or port forwarding changes should
not have any impact.
If all the services are running and the miner has a good internet
connection, there is no reason for it not to work.

**Comment by shawaj** [comment]
Closing this now as probably not relevant anymore after relaying / P2P stuff removed earlier in the year
