### ISSUE TITLE
Nebra Daskboard

### ISSUE THREAD

**Issue by ronmis** [NebraLtd/helium-rak#14]
Has the dashboard been enabled for RAK's yet? I tried adding my RAK using the serial number and ethernet / wifi mac id and it didn't work.

**Comment by Crash0v3r1de** [comment]
Nebra's dashboard is a paid service (I'm sure the dev will communicate that at some point). If you want to aaccess your device through Balena's dashboard you need to fork the fleet into your own then flash with your fleets image.

**Comment by shawaj** [comment]
@ronmis not yet no, we are still planning to enable this at some point

**Comment by shawaj** [comment]
@ronmis @Crash0v3r1de you can now claim your devices in Nebra dashboard when using third party software.

Just go to the diagnostics page and click on the things Network or Mysterium and you then get prompted with the option to add your device to the dashboard and start your free trial

Please note that your device needs to be running on Nebra fleets. If you are running the device in your own balenaCloud fleet this will not work.
