### ISSUE TITLE
Enable mux and disable chain sync in sys.config

### ISSUE THREAD

**Issue by ifeign** [NebraLtd/helium-rak#15]
Upon checking sys.config, it appears two options are not set correctly for the miner: 

`   {gateway_and_mux_enable, false},
   {gateways_run_chain, true}, %% if false, gateways will no longer follow the chain`

Should be

`   {gateway_and_mux_enable, true},
   {gateways_run_chain, false}, %% if false, gateways will no longer follow the chain`

**Comment by pritamghanghas** [comment]
What release are you running. This was changed last week.

**Comment by ifeign** [comment]
The latest build, 335bee3. This is in the miner container,
/config/sys.config. I noticed that the first release that contained the
2022.07.14 firmware had mux enabled but still was syncing. Every build of
yours since has shown the above, mux disabled, sync enabled.

**Comment by pritamghanghas** [comment]
that is base config I think. we override that config with
/opt/miner/releases/2022.07.14.0/sys.config

that should have the right settings.

Regards,
Pritam

**Comment by ifeign** [comment]
> that is base config I think. we override that config with /opt/miner/releases/2022.07.14.0/sys.config that should have the right settings. Regards, Pritam
>

My mistake, you're correct. That config file is set up properly
