### ISSUE TITLE
Balenahub page empty

### ISSUE THREAD

**Issue by ifeign** [NebraLtd/helium-rak#18]
I noticed today that all of your fleets have disappeared from [Balenahub](https://hub.balena.io/organizations/nebraltd/) Has this project been discontinued?
<img width="1677" alt="Screenshot 2023-02-02 at 1 53 02 PM" src="https://user-images.githubusercontent.com/32289760/216435844-87d769ee-c28a-48c9-a4b3-0a9dc15fc85f.png">

**Comment by shawaj** [comment]
Duplicate of https://github.com/NebraLtd/helium-miner-software/issues/608
