### ISSUE TITLE
cant compile 

### ISSUE THREAD

**Issue by hellrc5** [NebraLtd/helium-rak#19]
Built many versions for my RAKs via Balena hub's fork button (last successful build 19th dec) but now that page is empty (already reported I know), so I tried to push it from github with the 'deploy with balena' icon which links to  https://dashboard.balena-cloud.com/deploy?repoUrl=https://github.com/NebraLtd/helium-rak

build starts but fails for the packer forwarder and multiplexer with the following error:

Service: packet-forwarder
[Error]                 Error: no matching manifest for linux/arm64/v8 in the manifest list entries
[Error]               Service: multiplexer
[Error]                 Error: no matching manifest for linux/arm64/v8 in the manifest list entries

my fleet is set up as rpi4 64bit (aarch64)

thank you for any heads up

**Comment by shawaj** [comment]
Can you show the error message and where it appears? Visa a screenshot or whatever

**Comment by shawaj** [comment]
Related to:
https://github.com/NebraLtd/helium-controllino/issues/5

**Comment by phewwy** [comment]
[Info]              Starting build for helium-rak, user “redacted”
[Info]              Dashboard link: https://dashboard.balena-cloud.com/apps/redacted/devices
[Info]              Building on arm02
[Info]              Pulling previous images for caching purposes...
[Success]           Successfully pulled cache images
[Info]              Uploading images
[Success]           Successfully uploaded images
[Error]             Some services failed to build:
[Error]               Service: packet-forwarder
[Error]                 Error: no matching manifest for linux/arm64/v8 in the manifest list entries
[Error]               Service: multiplexer
[Error]                 Error: no matching manifest for linux/arm64/v8 in the manifest list entries
[Info]              Built on arm02
[Error]             Not deploying release.

I added the word redacted in place of my fleet name

**Comment by shawaj** [comment]
@phewwy I need a screenshot of where you are seeing this and how you deployed it?

**Comment by phewwy** [comment]
> @phewwy I need a screenshot of where you are seeing this and how you deployed it?

![8BD31C64-03B9-4A71-A608-3641BB6ED77C](https://user-images.githubusercontent.com/105826367/216776571-7db57388-b9b9-4779-9e71-36560067a612.jpeg)
![698E41CA-E1B4-41F8-8663-819423F8E281](https://user-images.githubusercontent.com/105826367/216776575-cf66327c-3034-4548-8cfa-2942df66a059.jpeg)

**Comment by phewwy** [comment]
![BB180366-D49A-462A-B73D-DF4D5BF6B3E6](https://user-images.githubusercontent.com/105826367/216776686-a6388dfc-1609-4e65-9dc2-dec66e2d8a2a.jpeg)

**Comment by hellrc5** [comment]
![image](https://user-images.githubusercontent.com/124432349/216779037-aa27feeb-6897-4d1f-aa8c-748fc818e4fb.png)
![image](https://user-images.githubusercontent.com/124432349/216779071-5a25c10f-7664-4b5b-8af1-005cbd75f0eb.png)

**Comment by shawaj** [comment]
Thanks for the detailed screenshots @phewwy and @hellrc5 

It seems Balena changed something which broke this.

However I have a fix incoming, probably tomorrow (Sunday)

**Comment by shawaj** [comment]
@phewwy @hellrc5 it's in testnet now. Once tested I'll promote it to production and then it should work for you.

I'll keep you posted

**Comment by shawaj** [comment]
Reopening as pyhelper is failing currently

**Comment by phewwy** [comment]
> @phewwy @hellrc5 it's in testnet now. Once tested I'll promote it to production and then it should work for you.
> 
> I'll keep you posted

Awesome, thanks for deep diving into this!

**Comment by shawaj** [comment]
ok it is working on testnet now with the updated hm-pyhelper build https://github.com/NebraLtd/helium-miner-software/pull/616/commits/f6f68d6b239871a739ef32eeaf6094e5f7c04d53

Will merge to production soon too

**Comment by shawaj** [comment]
Closed by https://github.com/NebraLtd/helium-miner-software/pull/616

@phewwy @hellrc5 could you try again? That should be fixed now for you

**Comment by phewwy** [comment]
Installed fine , thank you again for resolving this!

**Comment by shawaj** [comment]
Perfect, glad it's working now.

If you are finding our open source software useful then please consider sponsoring our efforts at https://github.com/sponsors/NebraLtd

And please share to others as well 🙂

We have lots of cool features coming up!

**Comment by hellrc5** [comment]
@shawaj  Thank you for working overtime to fix this, the build now runs with no errors, however the packet forwarder complains about the radio FREQ parameter:

 packet-forwarder  Error: Cannot set FREQ variable.
 packet-forwarder  VARIANT variable is already set as COMP-RAKHM.
 packet-forwarder  Error: Not all required parameters have been set. Container will be reset after 5 sec.

Interestingly the diagnostics container detects the correct FREQ plan:

 diagnostics  INFO:hw_diag.utilities.hardware:Found the following LTE Devices: []
 diagnostics  INFO:root:Frequency: EU868

TBH I don't think the packer-forwarder will do too much work if the container resets every 5 sec. 

Other issue I noticed that I cannot ping the device on my LAN anymore and the lack of web interface on the local IP, I can live with that because the PUBLIC DEVICE URL works fine via Balena

![image](https://user-images.githubusercontent.com/124432349/216846792-ebdac753-1c5a-43b6-9ae6-2c91519736ee.png)

**Comment by hellrc5** [comment]
@shawaj Okay packer forwarder looks better after adding this, lets see if we can generate some traffic now:

![image](https://user-images.githubusercontent.com/124432349/216847268-9acb445b-29bb-424c-9db9-191df32e17e0.png)

**Comment by shawaj** [comment]
@hellrc5 it sounds like there's something wrong with the environment variables setup.

Can you add user gh_shawaj to have access to the device please? Then I can take a look and see if I can see any issues

**Comment by shawaj** [comment]
I've found the issue @hellrc5 - thanks

It's related to this https://github.com/NebraLtd/hm-pktfwd/blob/master/setenv_pktfwd.sh

**Comment by hellrc5** [comment]
@shawaj 

> Can you add user gh_shawaj to have access to the device please? Then I can take a look and see if I can see any issues

added you, feel free to have a look

**Comment by shawaj** [comment]
Thanks @hellrc5 - I've found the issue. Created another issue in the correct repo https://github.com/NebraLtd/hm-pktfwd/issues/123

Will push a fix ASAP

**Comment by shawaj** [comment]
Also @hellrc5 I fixed the issue with the config containers on your fleet.

Any new devices your add should be ok by default now

Was the same as...
https://github.com/NebraLtd/hm-config/issues/233

**Comment by hellrc5** [comment]
@shawaj 
> Also @hellrc5 I fixed the issue with the config containers on your fleet.

thanks very much, I had to power cycle this local machine but after it pulled the new build I can ping it again and local dashboard is okay again.

**Comment by hellrc5** [comment]
@shawaj hey thanks for fixing the gateway-config container too, it kept crashing for the past half a year with every build for everyone I know :D  that's the reason I usually kept it stopped

**Comment by shawaj** [comment]
> @shawaj hey thanks for fixing the gateway-config container too, it kept crashing for the past half a year with every build for everyone I know :D that's the reason I usually kept it stopped

The issue with the config was a missing parameter in the device configuration device tree overlay setting you need to have `"spi0-1cs","vc4-kms-v3d"` (with the quote marks)

The spi0-1cs bit was missing on yours. Actually, you had it on the fleet level but not on the device level.

If you know anyone with the same problem, the same thing should fix it :-)

**Comment by shawaj** [comment]
> @shawaj hey thanks for fixing the gateway-config container too, it kept crashing for the past half a year with every build for everyone I know :D that's the reason I usually kept it stopped

@hellrc5 the issue with the config was a missing parameter in the device configuration "Define DT overlays" setting you need to have `"spi0-1cs","vc4-kms-v3d"` (with the quote marks)

The spi0-1cs bit was missing on yours. Actually, you had it on the fleet level but not on the device level.

If you know anyone with the same problem, the same thing should fix it :-)

**Comment by shawaj** [comment]
Also just FYI @hellrc5 you can remove me from the fleet now if you want as all looking good 😊
