### ISSUE TITLE
No fleet on balena hub

### ISSUE THREAD

**Issue by uros76** [NebraLtd/helium-rak#20]
Hi. Did something happen with Rak fleet? It's not on balena hub anymore 😒
This link [nebra.io/rak](https://nebra.io/rak) gives me an `error: failed to fetch resource`

**Comment by shawaj** [comment]
Duplicate of https://github.com/NebraLtd/helium-miner-software/issues/608

**Comment by shawaj** [comment]
Duplicate of #18
