### ISSUE TITLE
Diagnostics - Device health check: User service 'packet-forwarder' is restarting unexpectedly, count: 166

### ISSUE THREAD

**Issue by VanThongTomTo** [NebraLtd/helium-rak#3]
After running the device health check on my rak v2, I get that error: 
![image](https://user-images.githubusercontent.com/52040035/158371075-ba30942f-fe9d-48ac-a537-77294843c4fe.png)

Here are the logs:
[helium-rak_brave-doorway-15.03.22_12_41_33_(+0100).txt](https://github.com/NebraLtd/helium-rak/files/8252912/helium-rak_brave-doorway-15.03.22_12_41_33_.%2B0100.txt)

Here's the device diagnostic log:
[4bd2b596ecc33800175d40b8ff48b6b9_diagnostics_2022.03.14_15.40.28+0000.txt](https://github.com/NebraLtd/helium-rak/files/8253051/4bd2b596ecc33800175d40b8ff48b6b9_diagnostics_2022.03.14_15.40.28%2B0000.txt)

**Comment by arduino43** [comment]
You need to add the variable "VARIANT" in the Balena.io configuration and set the value to the hardware you are using, in your case "COMP-RAKHM"

**Comment by shawaj** [comment]
What is the "device health check" you are referring to?

**Comment by shawaj** [comment]
> You need to add the variable "VARIANT" in the Balena.io configuration and set the value to the hardware you are using, in your case "COMP-RAKHM"

You shouldn't need to do this, if you deploy using the fleet at https://nebra.io/rak as it's already in there

**Comment by shawaj** [comment]
@VanThongTomTo any update on my question above?

**Comment by shawaj** [comment]
Closing as no reply
