### ISSUE TITLE
Waveshare Module SX1302

### ISSUE THREAD

**Issue by rieders** [NebraLtd/helium-rak#4]
Hello
I have a question.
Is it possible to use Blena Rak with a concentrator SX 1302 module from Waveshare in connection with a security chip ATCC 608 on the I2c bus?
I would be happy if that works. I would also load the $55 on the wallet to start.

Many thanks for the help

**Comment by shawaj** [comment]
@rieders unfortunately DIY gateways are not possible at this time so you can't just make your own hardware.

It would probably work with the waveshare module as a data only hotspot but you wouldn't be able to mine HNT using this method.
