### ISSUE TITLE
Fast Sync not happening

### ISSUE THREAD

**Issue by ronmis** [NebraLtd/helium-rak#6]
I forked the repo from here - https://hub.balena.io/nebraltd/helium-rak and installed the image on my Rak v2 this morning, it's been a few hours and sync percentage is 0.17%, I was hoping it would fast sync by now.  Rak is hardwired.
VARIANT is set to COMP-RAKHM

**Comment by shawaj** [comment]
You don't need to fork the fleet. You just need to install directly from https://nebra.io/rak

**Comment by shawaj** [comment]
The fast sync won't work unless you install it from the above link.

**Comment by ifeign** [comment]
> The fast sync won't work unless you install it from the above link.

This is false.

**Comment by shawaj** [comment]
@ifeign sorry but you are wrong.

Additionally, hotspots don't need to sync anymore after the light hotspot upgrade 🙏

**Comment by ronmis** [comment]
@shawaj 

https://nebra.io/rak redirects to https://hub.balena.io/nebraltd/helium-rak

I wanted to fork the fleet so that I can view stats (temp, cpu, mem etc) of my miner on my personal balena dashboard. If I don't fork it, I believe my miner will get added to Nebra's fleet and I won't have access to that info

Will my miner receive updates as and when Nebra releases a new Firmware version? The check for updates is set to 10 minutes I believe. Or will I have to reflash everytime there is an update?

My miner finally caught up and is at 99.77 for the last few hours now.

Also I keep seeing the following error in the Dashboard Logs, anything you can do about it?
gateway-config  RuntimeError: Failed to add edge detection

**Comment by shawaj** [comment]
If you fork the fleet you will not get any updates.

You need to install to our fleet to get updates

**Comment by bodski1981** [comment]
@shawaj 

Can you confirm if adding the hotspot to Nebra's fleet that we are able to have the same control as a forked fleet?

I have also noticed the same error on my forked dashboard after applying the latest release to my fleet 
gateway-config RuntimeError: Failed to add edge detection

**Comment by shawaj** [comment]
You will not have the same control as a forked fleet no.

But that's the trade off... Use our fleet and get the instant sync, automatic updates etc etc or use your own and you would have to implement this all yourself.

Essentially, we have done all the heavy lifting for you

**Comment by ronmis** [comment]
@shawaj Would you happen to know when "remote management dashboard support via our Nebra dashboard" (https://www.nebra.com/blogs/news/production-update-firmware-support-for-third-party-miners-spring-sale-existing-customer-discount-and-more) will be provided to 3rd party miners?

**Comment by shawaj** [comment]
@ronmis we are working on it as we speak but we are looking at (approximately) 4 to 6 weeks before it's ready 🙌

**Comment by ronmis** [comment]
@shawaj Thank you! that's great news. Let me know if you need a beta tester

**Comment by foltz61** [comment]
Fast Sync definitely not working. I know it shouldn't be that big of a deal because of light hotspots but it's still nice to see that 100%. Especially now when the network is so messed up.

**Comment by ronmis** [comment]
@foltz61 did you fork it or click Get Started here https://hub.balena.io/nebraltd/helium-rak , Download BalenaOS and flash to a sd card? I did the later and it took a few hours to sync, but has been at 100% ever since, usually a block or two ahead. OS also got updated automatically.

**Comment by foltz61** [comment]
@ronmis I used the link.

**Comment by foltz61** [comment]
This is after about 15 hours. It started at 99.75%

![Screenshot_20220523-124036](https://user-images.githubusercontent.com/1285465/169867811-52bfa341-b6c5-4644-84d5-64a8d3aba046.png)

**Comment by foltz61** [comment]
8 hours later and still only another .05%. It's no big deal because I'm witnessing and beaconing. But if it's supposed to fast sync it's not :).
![Screenshot_20220523-203058](https://user-images.githubusercontent.com/1285465/169925439-54e4d88f-891c-4a8d-a08d-1fe0d3d233d2.png)

**Comment by shawaj** [comment]
As stated previously, it doesn't need to sync at all anymore 👍

**Comment by foltz61** [comment]
👍

**Comment by ronmis** [comment]
> @ronmis we are working on it as we speak but we are looking at (approximately) 4 to 6 weeks before it's ready 🙌

@shawaj Is the dashboard ready yet :) Waiting to try it out.
