### ISSUE TITLE
Image changes MAC address

### ISSUE THREAD

**Issue by foltz61** [NebraLtd/helium-rak#7]
Using this image changed my MAC address from what it was on the official Rak firmware. Is this normal? I would have never noticed if my hotspot hadn't showed it was relayed and I checked my port forwarding.

**Comment by Crash0v3r1de** [comment]
> Using this image changed my MAC address from what it was on the official Rak firmware. Is this normal? I would have never noticed if my hotspot hadn't showed it was relayed and I checked my port forwarding.

It is very normal to have balena use a different MAC then the RAK images. Adjust your networking, if you stay on this fleet (which you should) it won't change again unless balena causes it to - which I doubt will happen.

**Comment by foltz61** [comment]
I'm definitely staying on this image. I thought MAC's were actually embedded iin hardware. That's what threw me off. I do know they can be spoofed though. Thanks for the info.

**Comment by Crash0v3r1de** [comment]
> I'm definitely staying on this image. I thought MAC's were actually embedded iin hardware. That's what threw me off. I do know they can be spoofed though. Thanks for the info.

they are but who knows what janky setup RAK is doing with their balena images.
