### ISSUE TITLE
Can't update Wifi connection.

### ISSUE THREAD

**Issue by foltz61** [NebraLtd/helium-rak#8]
After activating Bluetooth by power cycling the hotspot and connecting, I am unable to change my WiFi connection. When you select a new SSID it just spins.

Edit:
This is with the Helium app and Hotspot Utility.

**Comment by foltz61** [comment]
Looks like this is an abandoned project.

**Comment by Turb0n00by** [comment]
> 

There is a 3rd party app out there called Hotspot Utility that you can try.

**Comment by foltz61** [comment]
Already tried that. Only way to do it is to remove the card and edit the config file. I've stopped using the firmware for now.

**Comment by Turb0n00by** [comment]
> Already tried that. Only way to do it is to remove the card and edit the config file. I've stopped using the firmware for now.

Did you go back to the OE image from RAK? Did you ever get this image to work for you at all?

**Comment by foltz61** [comment]
The Nebra firmware worked but I did go back to the OE Rak firmware.

**Comment by Turb0n00by** [comment]
> The Nebra firmware worked but I did go back to the OE Rak firmware.

Thanks for the info. I went back because this image never really worked right for me.

**Comment by shawaj** [comment]
The Bluetooth button and WiFi work fine.

You should use the RAK hotspot app not the Helium app though

And no this is not an abandoned project :-)

Please provide more information on how you installed it and the actual errors you were seeing with screenshots and error messages etc?

We need more details.

**Comment by shawaj** [comment]
Also please share what version of the RAK miner you are using, preferably with pictures as well

**Comment by foltz61** [comment]
I'm using the MNTD Blackspot. The Bluetooth button definitely wasn't working because Bluetooth was only available by the unplug/plug in method. 

I don't think there's a Rak app available yet.

**Comment by shawaj** [comment]
How were you running the software? Did you install it through https://nebra.io/rak ?

**Comment by shawaj** [comment]
Think this is working fine so closing
