### ISSUE TITLE
Can't activate Bluetooth via the side button.

### ISSUE THREAD

**Issue by foltz61** [NebraLtd/helium-rak#9]
I am unable to activate my Bluetooth by pressing the side button

**Comment by Turb0n00by** [comment]
I also have this issue. I have tried both the official and unofficial hotspot applications on iOS. It looks like the device is not enabling the pairing process.

**Comment by shawaj** [comment]
What generation of rak/mntd miner are you using? Can you share a picture?

**Comment by Turb0n00by** [comment]
> What generation of rak/mntd miner are you using? Can you share a picture?

Hey there, I am using the MNTD v2 blackspot. When attempting to pair with BT the device never shows up as discoverable. If I swap back to the OEM image I can pair normally again.

**Comment by foltz61** [comment]
Same here

**Comment by shawaj** [comment]
How were you running the software? Did you install it through https://nebra.io/rak ?

**Comment by Turb0n00by** [comment]
> How were you running the software? Did you install it through https://nebra.io/rak ?

Correct. Per the guide(s) I was given, I forked the fleet and flashed to SD card using Balena etcher.

**Comment by shawaj** [comment]
If you forked the fleet, then that's incorrect.

You just need to click the "get started" button on that page and download the image and flash it

**Comment by foltz61** [comment]
I didn't fork the fleet and the button didn't work. Shouldn't the button work if you fork the fleet though? I thought not forking the fleet just allowed Nebra to push updates instead of manually doing them yourself.

**Comment by shawaj** [comment]
Yes but then you have to manually add various fleet variables and a number of other more involved configuration steps.

The button works if you didn't fork the fleet.

You have to hold it for around 10 seconds though

**Comment by foltz61** [comment]
Oh. That wasn't the case with the OE firmware. I'll give it a try tomorrow and update the issue and close if it works. Thanks for the info.

**Comment by shawaj** [comment]
No problem. It's on our list to improve the documentation surrounding this but we have been a bit busy I'm afraid!

**Comment by ifeign** [comment]
> Yes but then you have to manually add various fleet variables and a number of other more involved configuration steps.
> 
> The button works if you didn't fork the fleet.
> 
> You have to hold it for around 10 seconds though

Is there any documentation yet regarding these various fleet variables? To my knowledge, all you need to get a forked fleet to be functional is to set the correct `VARIANT`, in this case `COMP-RAKHM`

That said, I don't need the button to work, but it wouldn't hurt.

**Comment by Turb0n00by** [comment]
> > Yes but then you have to manually add various fleet variables and a number of other more involved configuration steps.
> > The button works if you didn't fork the fleet.
> > You have to hold it for around 10 seconds though
> 
> Is there any documentation yet regarding these various fleet variables? To my knowledge, all you need to get a forked fleet to be functional is to set the correct `VARIANT`, in this case `COMP-RAKHM`
> 
> That said, I don't need the button to work, but it wouldn't hurt.

As far as I’m aware it’s just making sure you set the device variant as well.

**Comment by shawaj** [comment]
@ifeign yes that's correct

**Comment by foltz61** [comment]
I can confirm that holding the button down does activate Bluetooth. Unfortunately you can't connect to it with the Helium or Hotspot Utility apps. There's no Rak app to test with. Also, the available apps were not able to connect to the hotspot for some reason. They were able to a few weeks ago. The official Helium app just loses the connection. Hotspot Utility keeps connecting and disconnecting on it's own. 

Thanks

**Comment by shawaj** [comment]
The Bluetooth connection works for me using both the Helium app and our Nebra app.

Do you get an error message?

**Comment by foltz61** [comment]
On the Helium app it 
![Screenshot_20220614-153409~2](https://user-images.githubusercontent.com/1285465/173676669-7a159cdd-c14f-4540-957b-d5d2c085c5e2.png)
says "Something went wrong*.

**Comment by shawaj** [comment]
@NebraLtd/device-team could you take a look at this on a rak device?

**Comment by shawaj** [comment]
@foltz61 @Turb0n00by @ifeign @uros76 do you still get this error at all?

Seems to be working ok for me

**Comment by uros76** [comment]
> @foltz61 @Turb0n00by @ifeign @uros76 do you still get this error at all?
> 
> Seems to be working ok for me

I never tried that. I always onboarded my mntd hotspots with stock firmware and then flashed nebra

**Comment by shawaj** [comment]
@uros76 have you tried activating Bluetooth and connecting to the app at all? Like for changing WiFi or looking at diagnostics etc

**Comment by foltz61** [comment]
I went back to stock firmware a long time ago :).

**Comment by uros76** [comment]
> 
Not really, I use balena private fleet as my primary dashboard for my MNTD hotspots

**Comment by shawaj** [comment]
Ah ok, I'll close this issue for now then. As far as I can tell the Bluetooth is working fine
